# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(561, 301)
        self.listChat = QtWidgets.QListWidget(parent=Form)
        self.listChat.setGeometry(QtCore.QRect(10, 10, 151, 281))
        self.listChat.setObjectName("listChat")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(170, 10, 51, 16))
        self.label.setObjectName("label")
        self.nro_re = QtWidgets.QLabel(parent=Form)
        self.nro_re.setGeometry(QtCore.QRect(230, 10, 121, 16))
        self.nro_re.setObjectName("nro_re")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(170, 40, 51, 16))
        self.label_2.setObjectName("label_2")
        self.mensa_re = QtWidgets.QLabel(parent=Form)
        self.mensa_re.setEnabled(True)
        self.mensa_re.setGeometry(QtCore.QRect(230, 40, 321, 101))
        font = QtGui.QFont()
        font.setKerning(True)
        self.mensa_re.setFont(font)
        self.mensa_re.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignTop)
        self.mensa_re.setObjectName("mensa_re")
        self.respuesta = QtWidgets.QTextEdit(parent=Form)
        self.respuesta.setGeometry(QtCore.QRect(170, 150, 381, 111))
        self.respuesta.setObjectName("respuesta")
        self.enviar = QtWidgets.QPushButton(parent=Form)
        self.enviar.setGeometry(QtCore.QRect(330, 270, 75, 24))
        self.enviar.setObjectName("enviar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Chat"))
        self.label.setText(_translate("Form", "Número:"))
        self.nro_re.setText(_translate("Form", "Número:"))
        self.label_2.setText(_translate("Form", "Mensaje:"))
        self.mensa_re.setText(_translate("Form", "Mensaje:"))
        self.enviar.setText(_translate("Form", "Enviar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
